### ISSUE TITLE
Add Icons

### ISSUE THREAD

**Issue by KunalParihar** [itslenny/jquery-quiccordion#1]
Hi,

It will more help full if you add icons on close or open. In your further ver.

**Comment by itslenny** [comment]
Hi,

This plugin is meant to be as light-weight as possible. As such, no graphics or css are included, but classes are assigned to open / closed items to make it easy to add that. The easiest way would be to simply add a down arrow background to the "a" tag and have it change to a right arrow with the "closed" class.

#accordion .has-children>a{
background: url(downarrow.png) no-repeat
}

#accordion .has-children.closed>a{
background: url(leftarrow.png) no-repeat
}

I just updated the demo.html to include simple css arrows for the open / closed states since I don't want to include images.

cheers,

Lenny
